### ISSUE TITLE
GitHub Actions Marketplace links to the wrong repository

### ISSUE THREAD

**Issue by brandones** [c2corg/transifex-pull-request-action#129]
Looks like it needs to be updated? https://github.com/marketplace/actions/transifex-pull-request-action

**Comment by brunobesson** [comment]
Hello, sorry for the delay answering, I was on vacation.
Could you be more explicit? Which link are you referring to?

**Comment by brandones** [comment]
I'm referring to the link in the comment. Again, it's https://github.com/marketplace/actions/transifex-pull-request-action

If you navigate to that link, you will see something like this:

![Screenshot from 2021-09-07 13-24-27](https://user-images.githubusercontent.com/1031876/132406257-37a18133-c29b-4017-ae1f-441ce24db6e9.png)

**Comment by brunobesson** [comment]
Oh! I finally get it, thanks. Huge mistake, sorry. I'll fix it.
