### ISSUE TITLE
Non reviewed strings are exported

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/transifex-pull-request-action#133]
On transifex, russian lang is reviewed at 30%, and almost entirely translated https://www.transifex.com/camptocamp-association/c2corg_ui/dashboard/

But it seems that all strings are exported.

**Comment by brunobesson** [comment]
Yes, it's a design choice. Apart from a few people, most translators don't
use it. I considered it thus harmful.

**Comment by cbeauchesne** [comment]
ok for me!
